import Head from 'next/head';
import Login from '@/authcomp/Login';


const Auth=()=>{
return(
    <>
     <Head>
        <title>Kayana</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />

      </Head>
      <Login/>
    </>
)

}
export default Auth;