import Navbar from '@/components/nav';
import Head from 'next/head';
import FooterBottom from '@/components/FooterBottom';
import GetStarted from '@/startcomp/GetStarted';


const Started=()=>{
return(
    <>
     <Head>
        <title>Kayana</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar/>
      <GetStarted/>
      <FooterBottom/>
      
    </>
)

}
export default Started;